version: '3.8'

services:
  ncode-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ncode-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SERVER_CONTEXT_PATH=/
      - DATABASE_URL=jdbc:postgresql://postgres:5432/ncodegestion
      - DATABASE_USERNAME=ncode_user
      - DATABASE_PASSWORD=N0l0s4br4s.
    depends_on:
      - postgres
    networks:
      - ncode-network

  postgres:
    image: postgres:16-alpine
    container_name: ncode-postgres
    environment:
      - POSTGRES_USER=ncode_user
      - POSTGRES_PASSWORD=N0l0s4br4s.
      - POSTGRES_DB=ncodegestion
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ncode-network

volumes:
  postgres-data:

networks:
  ncode-network:
    driver: bridge

